version: '3.6'  
services:
  i_finances_frontend:
    image: renanllm/i-finances-frontend
    depends_on:
      - i_finances_backend
    environment:
      - REACT_APP_URL_BACKEND=http://i_finances_backend:5000/api
    ports:
      - "3000:80"
  i_finances_backend:
    image: renanllm/i-finances-backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database/i_finances
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
  database:
    image: mongo
    volumes:
      - mongo_data:/data/db
volumes:  
  mongo_data: